language:  java
#travis setup releases --com
jdk:
    #- oraclejdk8
    - openjdk8
git:
    quiet: true


# blocklist
branches:
    except:
    - release

delpoy:
    provider: releases 
    api_key: "GITHUB OAUTH TOKEN"
    file: "FILE TO UPLOAD"
    skip_cleanup: true
    on:
        all_branches: true
        branch: release