language:  java
jdk:
    #- oraclejdk8
    - openjdk8
git:
    quiet: true


# blocklist
branches:
    except:
    - release


delpoy:
    all_branches: true
    api_key: "GITHUB OAUTH TOKEN"
    file: "FILE TO UPLOAD"
    skip_cleanup: true
    on:
        branch: release