language:  java
jdk:
    #- oraclejdk8
    - openjdk8
git:
    quiet: true


# blocklist
branches:
    only:
    - master

travis setup releases
delpoy:
    provider: releases 
    api_key: "GITHUB OAUTH TOKEN"
    file: "FILE TO UPLOAD"
    skip_cleanup: true
    on:
        all_branches: true
        branch: release