language: java
git:
  quiet: true
branches:
  except:
  - release
  
services:
  - docker


before_deploy:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker build -t pierremarchetti/projetdevops2 .
    
deploy:
  - provider: releases
    api_key:
        secure: aqMbauthmMefVryNxR3GDxMIhEU9sIOYPFkZ68PUNf/OZcyC3Np3JzHrI70TdjHDTS8kUVqWqP8bjQ3mpxwqtSwSbkKuz4DtpGYgsc2rbxiODwuEmBjNsPNfTOLjI+hpku5w+6W2V/2DJWUiz6seR/FnwFoY7hIs2aduX32CxBal17sIN+9n57HdWwBs2uGmkm+jKWDFGY90QjD2cUYy09fTXsHh2OQD71eAxD5VPJ+io3fz1+UTXEwYl8nJRgFWI9R3kapyVSScELAZuZfo9Os1yWUzPrAkYVGzSIP2OTv6t9FKVhTx/0R30SWB4U6Uvurbp+NDoQVVYl4G5CYGdWPGj34zSHi4smtLp2qrYujnmm36/B796XUNmnRHSbK+FNNiC0Y+RptOMftnP7U6zcRRfXRfMuA7Gc9L+K1T0e/CeTQNvXyGzEtAarBJXMerZM3vx0yPQFv01o19qvrIFycodIGWSu0cMJshaHNEGGmB+NgJkhGR6xKMCjm0Xnxo+YlYO4iGlTT7TCxg5W4g5mErIsqLz9ATo+AA2hNcasBp5Rhoiyaa+gUkmh6cW/xB4Tyaw4PajT3cifqr4V94gK+R2ltN/ADhthWwcDuE0IKLMLyZ49bAaK8RQgfN+GwTJG0ZpDszMV31JIAYvDzBzXYp4OrtVi9/aey7zs4gE4g=
  - provider: script
    script:  docker push pierremarchetti/projetdevops2

after_success:
  - bash <(curl -s https://codecov.io/bash)